name: acuses
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  http: ^0.13.3
  sqflite: ^2.0.0
  path_provider: ^2.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  uses-material-design: true
  assets:
    - assets/textura.jpg
    - assets/logo.png
    - assets/fondo.png
    - assets/fondo2.png
